# Generated by Django 5.1.6 on 2025-02-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='oid',
            field=models.CharField(blank=True, default='81B5Kkhk', editable=False, max_length=9, null=True, unique=True),
        ),
    ]
