# Generated by Django 5.1.6 on 2025-02-06 19:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_oid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='oid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
